name: CD Single Service

on:
  workflow_dispatch:
    inputs:
      service:
        type: choice
        description: 'service:'
        options:
        - road-registry-projector
        - road-registry-backoffice-api
        - road-registry-backoffice-ui
        - road-registry-backoffice-extracthost
        - road-registry-backoffice-commandhost
        - road-registry-backoffice-messaginghost-sqs
        - road-registry-backoffice-eventhost
        - road-registry-editor-projectionhost
        - road-registry-syndication-projectionhost
        - road-registry-product-projectionhost
        - road-registry-wms-projectionhost
        - road-registry-wfs-projectionhost
        default: road-registry-backoffice-api
      env:
        type: choice
        description: 'environment:'
        options:
        - test
        - stg
        - prd
        default: stg
      version:
        description: 'Version'     
        required: true
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: CD
      env:
        BUILD_URL: ${{ secrets.VBR_AWS_BUILD_API }}/${{ github.event.inputs.service }}
        STATUS_URL: ${{ secrets.VBR_AWS_BUILD_STATUS_API }}/${{ github.event.inputs.service }}
      uses: informatievlaanderen/awscurl-polling-action/polling-action@main
      with:
          environment: ${{ github.event.inputs.env }}
          version: ${{ github.event.inputs.version }}
          status-url: $STATUS_URL
          deploy-url: $BUILD_URL
          access-key: ${{ secrets.VBR_AWS_BUILD_USER_ACCESS_KEY_ID }}
          secret-key: ${{ secrets.VBR_AWS_BUILD_USER_SECRET_ACCESS_KEY }}
          region: eu-west-1
          interval: 2
    - name: output
      shell: bash
      run: |
        echo build-uuid: ${{ steps.awscurl-polling-action.outputs.build-uuid }}
        echo Status: ${{ steps.awscurl-polling-action.outputs.status }}
        echo ${{ steps.awscurl-polling-action.outputs.final-message }}
